config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, only:[:index,:show,:new,:create] do
    member do
      get :likings
    end
  end
  resources :favorites, only:[:create,:destroy]
  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  validates :title, presence: true, length: {maximum: 25}
  validates :content, presence: true, length: { maximum: 255 }
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_validation {email.downcase!}
  has_many :posts
  has_many :favorites, dependent: :destroy
  validates :name, presence: true, length: {maximum: 25}
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private

  def require_user_login
    unless logged_in?
      redirect_to root_path
    end
  end

  def count(user)
    @count_posts = current_user.posts.count
    @count_favs = current_user.favorites.count
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(post_id: params[:post_id])
    flash[:success] ="#{favorite.post.user.name}さんのポストをお気に入り登録"
    redirect_to root_path
  end

  def destroy
    favorite = current_user.favorites.find_by(post_id: params[:id]).destroy
    flash[:danger] ="#{favorite.post.user.name}さんのポストをお気に入り解除"
    redirect_to root_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] ='Post made!!'
      redirect_to root_path
    else
      flash.now[:danger] ='Failed..'
      render 'toppages/index'
    end
  end

  def edit
    @post=current_user.posts.find_by(id: params[:id])
  end

  def update
    @post=current_user.posts.find_by(id: params[:id])
    if @post.update(post_params)
      flash[:success] ='Edit complete!'
      redirect_to root_path
    else
      flash.now[:danger] ='Failed..'
      render 'edit'
    end
  end

  def destroy
    @post=current_user.posts.find_by(id: params[:id])
    @post.destroy
    flash[:danger] ='Post deleted!!'
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title,:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] ='Logged in!!'
      redirect_to root_path
    else
      flash.now[:danger] ='Failed..'
      render 'new'
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:danger] ='Logout!!'
    redirect_to login_path
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
    if logged_in?
      @post = current_user.posts.build
      @posts = Post.all.order('created_at DESC').page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_login, only:[:index,:show]

  def index
    @users = User.all.page(params[:page])
  end

  def show
    @user = User.find(params[:id])
    @posts = current_user.posts.order('created_at DESC').page(params[:page])
    count(@user)
  end

  def likings
    @user = User.find(params[:id])
    @posts = Post.all.order('created_at DESC').page(params[:page])
    count(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] ='Signed up!!'
      redirect_to users_path
      # new_session_path
    else
      flash.now[:danger] ='Failed..'
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    @current_user ||=User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

end

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error_explanation">
    <h4><%= model.errors.count %>件のエラーがあります</h4>
  </div>
  <ul>
    <% model.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |type,msg| %>
  <div class="alert alert-<%= type %>"><%= msg %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to 'All Posts',root_path,class:"navbar-brand" %>
		</div>

		<div class="collapse navbar-collapse" id="navbarEexample1">
			<ul class="nav navbar-nav">
				<% if logged_in? %>
					<li><%= link_to 'My Profile',user_path(current_user.id) %></li>
					<li><%= link_to 'Logout',logout_path(current_user.id),method: :delete %></li>
				<% else %>
					<li><%= link_to 'Sign up',signup_path %></li>
					<li><%= link_to 'Login',login_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Post3</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= render 'layouts/flash_messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_posts.html.erb
<ul class="media-list">
  <% posts.each do |post| %>
	<li class="media">
		<h4 class="media-left" style="color: blue;">
      <% if post.user.id == current_user.id %>
        <%= link_to 'Edit',edit_post_path(post.id),class:'btn btn-info btn-xs' %>
        <%= link_to 'Dele',post_path(post.id),method: :delete,data: {confirm: 'Are you sure ?'},class:'btn btn-danger btn-xs' %>
      <% else %>
        <%= post.user.name %>:
        <% if current_user.favorites.pluck(:post_id).include?(post.id) %>
          <%= link_to 'お気に入りを解除',favorite_path(id: post.id),method: :delete,class:'btn btn-danger btn-xs' %>
        <% else %>
          <%= link_to 'お気に入りを登録',favorites_path(post_id: post.id),method: :post,class:'btn btn-success btn-xs' %>
        <% end %>
      <% end %>
		</h4>
		<div class="media-body">
			<h4 class="media-heading"><%= post.title %></h4>
			<%= post.content %>
		</div>
	</li>
  <% end %>
</ul>

app/views/posts/edit.html.erb
<h1>Edit Page</h1>
<%= form_with(model: @post,local: true)do |f| %>
<div class='post_group'>
  <%= f.label :title, 'title' %>
  <%= f.text_field :title, class:'form-control' %>
</div>

<div class='post_group'>
  <%= f.label :content, 'content' %>
  <%= f.text_area :content, class:'form-control',row:2 %>
</div>
<%= f.submit 'Edit Post',class:'btn btn-primary btn-lg' %>
<% end %>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>

app/views/posts/new.html.erb
<h1>Posts#new</h1>
<p>Find me in app/views/posts/new.html.erb</p>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<p>Find me in app/views/posts/show.html.erb</p>

app/views/toppages/index.html.erb
<% if logged_in? %>
	<p>Login user: <%= current_user.name %></p>
	<%= form_with(model: @post,local: true)do |f| %>
	<div class='post_group'>
		<%= f.label :title, 'title' %>
		<%= f.text_field :title, class:'form-control' %>
	</div>

	<div class='post_group'>
		<%= f.label :content, 'content' %>
		<%= f.text_area :content, class:'form-control',row:2 %>
	</div>
	<%= f.submit 'Create New Post',class:'btn btn-primary btn-lg' %>
	<% end %>

	<%= render 'posts/posts', posts: @posts %>

<% else %>
	<div class="jumbotron">
		<div class="container">
	    <h1>POST No.3</h1>
		</div>
	</div>
<% end %>

app/views/users/index.html.erb
<h1>Users index</h1>
<ul class="media-list">
  <% @users.each do |user| %>
	<li class="media">
		<div class="media-left" style="color: blue;">
			<h4>USER:</h4>
		</div>
		<div class="media-body">
			<h4 class="media-heading">Name: <%= user.name %></h4>
			Registered: <%= user.created_at %>
		</div>
	</li>
  <% end %>
</ul>

app/views/users/likings.html.erb
<h1>User Info.</h1>
<div class='row'>
  <div class='col-xs-4'>
    <div class="panel panel-default">
      <div class="panel-heading">
        NAME: <%= @user.name %>
      </div>
      <div class="panel-body">
        EMAIL: <%= @user.email %>
      </div>
    </div>
  </div>
  <div class='col-xs-8'>
    <ul class="nav nav-tabs">
    	<li role="presentation" class="<%= 'active' if current_page?(user_path(@user.id)) %>"><%= link_to user_path(@user.id) do %>My Posts<span class="badge"><%= @count_posts %></span><% end %></li>
    	<li role="presentation" class="<%= 'active' if current_page?(likings_user_path(@user.id)) %>"><%= link_to likings_user_path(@user.id) do %>My Favs<span class="badge"><%= @count_favs %></span><% end %></li>
    </ul>

    <ul class="media-list">
      <% @posts.each do |post| %>
      <% unless post.user.id == @user.id %>
          <% if current_user.favorites.pluck(:post_id).include?(post.id) %>
          	<li class="media">
          		<h4 class="media-left" style="color: blue;">
                    <%= post.user.name %>:
                    <%= link_to 'お気に入りを解除',favorite_path(id: post.id),method: :delete,class:'btn btn-danger btn-xs' %>
          		</h4>
          		<div class="media-body">
          			<h4 class="media-heading"><%= post.title %></h4>
          			<%= post.content %>
          		</div>
          	</li>
          <% end %>
        <% end %>
      <% end %>
    </ul>

  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with(model: @user,local: true)do |f| %>
<%= render 'layouts/error_messages',model: f.object %>

  <div class='user_group'>
    <%= f.label :name, 'name' %>
    <%= f.text_field :name, class:'form-control' %>
  </div>

  <div class='user_group'>
    <%= f.label :email, 'email' %>
    <%= f.email_field :email, class:'form-control' %>
  </div>

  <div class='user_group'>
    <%= f.label :password, 'password' %>
    <%= f.password_field :password, class:'form-control' %>
  </div>

  <div class='user_group'>
    <%= f.label :password_confirmation, 'confirmation' %>
    <%= f.password_field :password_confirmation, class:'form-control' %>
  </div>

  <%= f.submit 'Sign up!',class:'btn btn-primary btn-block' %>
<% end %>

app/views/users/show.html.erb
<h1>User Info.</h1>
<div class='row'>
  <div class='col-xs-4'>
    <div class="panel panel-default">
      <div class="panel-heading">
        NAME: <%= @user.name %>
      </div>
      <div class="panel-body">
        EMAIL: <%= @user.email %>
      </div>
    </div>
  </div>
  <div class='col-xs-8'>
    <ul class="nav nav-tabs">
    	<li role="presentation" class="<%= 'active' if current_page?(user_path(@user.id)) %>"><%= link_to user_path(@user.id) do %>My Posts<span class="badge"><%= @count_posts %></span><% end %></li>
    	<li role="presentation" class="<%= 'active' if current_page?(likings_user_path(@user.id)) %>"><%= link_to likings_user_path(@user.id) do %>My Favs<span class="badge"><%= @count_favs %></span><% end %></li>
    </ul>

    <%= render 'posts/posts', posts: @posts %>

  </div>
</div>